### ISSUE TITLE
Use serde (maybe) for minimum-copy (de)serialization 

### ISSUE THREAD

**Issue by BulbaWarrior** [invian/influx-line#1]
yes

**Comment by DOCtorActoAntohich** [comment]
sadly, this isn't the goal of the library, unless we change our mind in the future (which we could)

with some attribute shenanigans like in [telegraf-rust](https://github.com/maxmindlin/telegraf-rust#define-structs-that-represent-metrics-using-the-derive-macro) it's possible to avoid boilerplate and implement serialize/deserialize for almost any struct, but now we focus on other things
